version: '3'
services:
  app:
    environment: 
      - BUNDLE_PATH=/gems
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_SECRET=${SHOPIFY_SECRET}
    depends_on:
      - db
      - redis
    build: .
    volumes:
      - gems:/gems
    networks:
      - main
  db:
    image: postgres:10
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - main
  redis:
    image: redis
    networks:
      - main
  sidekiq:
    build: .
    volumes:
      - gems:/gems
    depends_on:
      - redis
      - db
      - app
    entrypoint:
      - bundle
      - exec
      - sidekiq
    environment: 
      - BUNDLE_PATH=/gems
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_SECRET=${SHOPIFY_SECRET}
    networks:
      - main
volumes:
  db-store:
  gems:
networks:
  main: