development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: app_dev
test:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: app_test

production:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: app_production
